### PR TITLE
Add Yannick Le Roux

### PR DESCRIPTION
**Pull request by YannickLeRoux**

### CODE REVIEW

**Comment by YannickLeRoux** [comment]
Sorry not sure whats going on... looks like my link works:  https://yannickleroux.com/uses

**Comment by sam-cross** [comment]
@YannickLeRoux I'm getting a 404 
image

**Comment by YannickLeRoux** [comment]
Thanks, I added a config file for netlify and it seems to work now....

**Comment by sam-cross** [comment]
Yup, all good now, adding!

**Pull request merged**
