### PR TITLE
Add Eliezer Steinbock

### PR DESCRIPTION
**Pull request by elie222**

### CODE REVIEW

**Comment by iamandrewluca** [comment]
Please add a valid `/uses` pages.

**Comment by thisisabdus** [comment]
Please resolve conflicts!

**Comment by iamandrewluca** [comment]
You are not allowed to remove, or edit other users data.

**Comment by elie222** [comment]
The current failure is a problem with the Wes Bos website:

```
##[error]Ping to "https://wesbos.com/uses" failed with error: Error: Request timed out
```

**Comment by wesbos** [comment]
weird - my own site was down? seems fine now - merged

**Comment by elie222** [comment]
> weird - my own site was down? seems fine now - merged

Ya... Seems like you've overloaded the Netlify servers with pings to `uses` websites 😂
https://github.com/wesbos/awesome-uses/runs/391832119

**Pull request merged**
