### PR TITLE
Add jordan.hofker.org/uses/

### PR DESCRIPTION
**Pull request by jhofker**
Not sure if a Mastodon handle will work, but let's find out!

✅ You've read and understood the above
**Add your name to verify:** Jordan Hofker

### CODE REVIEW

**Review by gatarelib — CHANGES_REQUESTED** [review]
The Twitter handle provided, "@jhofker@hachyderm.io", doesn't fit the expected format. It should only contain letters, numbers, or underscores, and be between 1 to 15 characters long.

**Comment by jhofker** [comment]
Updated to just use Twitter handle. Would be great to get #1593 going to support Mastodon!

**Comment by jhofker** [comment]
Hey @gatarelib when you have a moment, can you re-review? Thanks!

**Review by BlakeCampbells — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
