### PR TITLE
Added Lewis Shaw

### PR DESCRIPTION
**Pull request by WeaverOfTheWeb**

### CODE REVIEW

**Comment by HugoDF** [comment]
"Coming soon" huh? Would it be possible for that "uses" page to not be empty before we merge this?

**Comment by WeaverOfTheWeb** [comment]
> "Coming soon" huh? Would it be possible for that "uses" page to not be empty before we merge this?

Working on it tonight!

**Comment by iamandrewluca** [comment]
but why

**Comment by wesbos** [comment]
Stoked to have you, please just add the PR once it's up :)

**Pull request closed without merging**
