### PR TITLE
Add @solrevdev

### PR DESCRIPTION
**Pull request by solrevdev**
# awesome-uses

Please read the requirements corresponding to your pull request before you submit.

## What's a Uses Page?

A /uses page lists a developer's setup, gear, software, and configs (what they *use*). It's a great reference for those looking to add to their library of tools or reconfigure ones they already use.

### What Should I Include?

Include the hardware you use, such as your computer and other related equipment. Include your preferred terminal, text editors, tools, frameworks, and other related software you use. If you can, include configurations for software (such as fonts and themes). The more you have on your /uses page, the more interesting it'll be to those who view it - just keep it on-topic!

## Adding Yourself

* Ensure you are linking to a /uses page, **not just your website**
* Ensure your data is formatted like other entries
* Do not add yourself to the end of the array (add yourself somewhere random instead)
* Ensure this PR has a title in the following format
    * ✅ Add Your Name
    * ✅ Add @twitterusername
    * ❌ Add myself
    * ❌ Adding myself!
    * ❌ Add Your Name @twitter @github

## Code Modifications

* Ensure the code submitted is formatted similarly to existing code
* Ensure variable, method, function, and component names are clear and concise

## Final Requirements

* You've read and understood the above

**Add your name to verify:** 
John Smith @solrevdev

### CODE REVIEW

**Comment by sam-cross** [comment]
@HugoDF is the country flag correct? I'm on Win10 so it's just showing a black flag for me.

**Comment by solrevdev** [comment]
> @HugoDF is the country flag correct? I'm on Win10 so it's just showing a black flag for me.

It should be the English flag 🏴󠁧󠁢󠁥󠁮󠁧󠁿 , displays ok on macOS Mojave for me

**Comment by solrevdev** [comment]
> > @HugoDF is the country flag correct? I'm on Win10 so it's just showing a black flag for me.
> 
> It should be the English flag 🏴󠁧󠁢󠁥󠁮󠁧󠁿 , displays ok on macOS Mojave for me

ooh, interesting. the flag was correct in markdown but when I post its also black?

2020-01-21_12_33_03_flag

**Comment by solrevdev** [comment]
Hi all, I have updated the code to use the 🇬🇧 GB flag as that seems to render ok.

**Comment by solrevdev** [comment]
> image
> 
> Something's really not right here... I'm going to wait for a contributor with a Mac to check over this

yeah, I've tried using the GB 🇬🇧 flag as that seemed to render ok but validation failed saying I must use one of a suite of flags that I was able to <kbd>ctrl</kbd><kbd>f</kbd> so I tried to use the original English 🏴󠁧󠁢󠁥󠁮󠁧󠁿 flag that whilst black at least passed validation originally but now the build just fails?

No idea what I can be doing wrong.

**Comment by HugoDF** [comment]
There's an open issue about the flag #278

**Pull request merged**
