### PR TITLE
Add @JrGiant

### PR DESCRIPTION
**Pull request by Joshua-rose**
Joshua Rose

### CODE REVIEW

**Review by davidak — CHANGES_REQUESTED** [review]
please only edit the `data.js`. the other files are generated automatically

**Comment by davidak** [comment]
Congratulations to PR/Issue 1000!

**Comment by Joshua-rose** [comment]
also, I reverted the readme. please let me know if any more changes are needed for this awesome 😎site

**Review by davidak — APPROVED** [review]
LGTM

thanks for your contribution :sparkles:

**Pull request merged**
