### PR TITLE
Adding Swastik Baranwal

### PR DESCRIPTION
**Pull request by Delta456**
Adding **Swastik Baranwal**

### CODE REVIEW

**Comment by Delta456** [comment]
image


How do I display my profile picture? I thought it would automatically take from my GitHub profile.

**Comment by wesbos** [comment]
hmm yah that seems to have been removed at some point. Let me fix that

**Comment by wesbos** [comment]
Oh - we don't collect github profile data. That is why. TWitter is best, but the unavatar rate limits to 50 requests per day, and that isn't enough for us

**Comment by Delta456** [comment]
> Oh - we don't collect github profile data. That is why. TWitter is best, but the unavatar rate limits to 50 requests per day, and that isn't enough for us

Afaik Twitter API is paid so it may be better to default to GitHub if that is something which can be considered.

**Pull request merged**
