### PR TITLE
Update Scott Spence Uses URLs

### PR DESCRIPTION
**Pull request by spences10**
Updating my Uses URLs the current one points to an old domain, I've added a short link so I don't have to submit another PR is the URL changes again 👍

### CODE REVIEW

**Comment by davidak** [comment]
You only need to update `src/data.js`.

**Review by davidak — CHANGES_REQUESTED** [review]
You only need to update `src/data.js`.
The other files are generated automatically.

**Comment by spences10** [comment]
Cool! Reverted those files

**Comment by davidak** [comment]
I still see changes to the `readme.md`.

https://github.com/wesbos/awesome-uses/pull/946/files

**Pull request closed without merging**
