### PR TITLE
feat: add action to validate data.js

### LINKED ISSUE #141: Reject PR if invalid data
Need some way to reject the PR if the submitted data doesn't meet the shape and requirements of what we want.

Maybe convert to Typescript? 

Or can we do it with with PropTypes? 

Seems like a good use case for github actions

### PR DESCRIPTION
**Pull request by iamandrewluca**
Closes #141

### CODE REVIEW

**Comment by wesbos** [comment]
thanks - do you have example of this on your repo? Will it show up with the netlify stuff in a PR?

**Comment by iamandrewluca** [comment]
Yes, it will be like Netlify stuff

**Comment by wesbos** [comment]
thanks! testing it myself and it seems e._original should be e._object? I can fix it if so

**Comment by iamandrewluca** [comment]
I also observed this, but it worked. I think that Joi static types do not reflect real data.

**Comment by iamandrewluca** [comment]
As I see action is working well

**Comment by wesbos** [comment]
awesome! Im working on that now - adding some better errors too

**Pull request merged**
