### PR TITLE
Duncan McClean @damcclean

### PR DESCRIPTION
**Pull request by damcclean**
Duncan McClean

### CODE REVIEW

**Comment by sam-cross** [comment]
@damcclean For some reason, the Netlify build is failing, so I can't merge this at the moment.

The log shows this:

```
Error: /opt/build/repo/src/data.js:2438
8:14:57 PM:       country: '🏴󠁧󠁢󠁳󠁣󠁴󠁿'󠁢󠁳󠁣󠁴󠁿,
8:14:57 PM:                                ^
8:14:57 PM:   SyntaxError: Invalid or unexpected token
```

I think there's some invisible character on this line which is causing the build to break. Could you double-check it? Thanks!

**Comment by damcclean** [comment]
> @damcclean For some reason, the Netlify build is failing, so I can't merge this at the moment.
> 
> The log shows this:
> 
> ```
> Error: /opt/build/repo/src/data.js:2438
> 8:14:57 PM:       country: '🏴󠁧󠁢󠁳󠁣󠁴󠁿'󠁢󠁳󠁣󠁴󠁿,
> 8:14:57 PM:                                ^
> 8:14:57 PM:   SyntaxError: Invalid or unexpected token
> ```
> 
> I think there's some invisible character on this line which is causing the build to break. Could you double-check it? Thanks!

Hopefully should be fixed now!

**Comment by sam-cross** [comment]
@damcclean data looks fine now, but the flag is simply black for me, which is causing validation to fail. I'm on Windows 10, which has issues displaying regional flags.

@HugoDF could you take a look at this and check it over?

**Comment by damcclean** [comment]
> @damcclean data looks fine now, but the flag is simply black for me, which is causing validation to fail. I'm on Windows 10, which has issues displaying regional flags.
> 
> @HugoDF could you take a look at this and check it over?

Must be because it's a Scottish flag... I'll have to change it to a UK one.

**Comment by sam-cross** [comment]
@damcclean Changing it to UK should fix it. We've got an open issue (#278) at the moment about this, it's quite annoying!

**Pull request merged**
