### PR TITLE
Update data.js -  added douglas andreani

### PR DESCRIPTION
**Pull request by andreanidouglas**

### CODE REVIEW

**Comment by wesbos** [comment]
Please add an emoji instead of country code :)

**Comment by wesbos** [comment]
and only one emoji

**Comment by andreanidouglas** [comment]
humm. I added one emoji, it was the cat riding the dinosaur 🐱‍🐉, but for some reason, it dismembered it in two

**Comment by wesbos** [comment]
lol I had no idea there was a dino cat emoji! it's a combo (much like skintone and family emojis) 

Feel free to leave it in - i can figure out how to make ZWJ emojis work

**Pull request merged**
