### PR TITLE
Add 5am.is

### PR DESCRIPTION
**Pull request by 5amdotis**

### CODE REVIEW

**Comment by BlakeCampbells** [comment]
The only error I'm seeing is: ```"phone" must be one of [iphone, android, windowsphone, flipphone]``` 

I think you just need to remove the hyphen.

**Review by BlakeCampbells — CHANGES_REQUESTED** [review]
Remove the hyphen in `flip-phone` please.

**Comment by 5amdotis** [comment]
Sorry. Fixed!

**Review by BlakeCampbells — APPROVED** [review]

**Comment by BlakeCampbells** [comment]
Perfect thanks!

**Pull request merged**
