### PR TITLE
Add Dominic Ruggiero

### PR DESCRIPTION
**Pull request by mrhappyma**

### CODE REVIEW

**Comment by mrhappyma** [comment]
It seems that I am missing a picture, how can I add one or where does one get pulled from?

**Comment by BlakeCampbells** [comment]
> It seems that I am missing a picture, how can I add one or where does one get pulled from?

It takes the picture from GitHub as far as I remember.

**Comment by mrhappyma** [comment]
> > It seems that I am missing a picture, how can I add one or where does one get pulled from?
> 
> It takes the picture from GitHub as far as I remember.

image

this is not my profile picture...

**Comment by BlakeCampbells** [comment]
It's defined in `src/components/Person.js` lines 24-30 the image either comes from Twitter or tries to grab it from your website.

**Comment by BlakeCampbells** [comment]
@mrhappyma Would you like me to merge this in now? Or did you want to update your profile picture?

**Comment by mrhappyma** [comment]
Sure, you can merge this now.

**Pull request merged**
