### PR TITLE
Cleanup Feb 2022

### PR DESCRIPTION
**Pull request by BlakeCampbells**
Blake Campbell: Cleaning the following sites either no longer exist or the `/uses` page is gone. 

If you would like to be re-added, please submit a new PR. I've tried to separate each removal into individual commits to keep it accessible to see what was removed. 

@famiclone 
@kushanshamika 
@boardfish 
@Mozart409 
@samirmhsnv 
@joshfarrant
@jakeherp 
@OneMohrTime

### CODE REVIEW

**Review by OneMohrTime — COMMENTED** [review]
@BlakeCampbells Hey! I just got this notification, and I do still have a `/uses` page, but it was moved to `/about/uses`. I just fixed the redirect, if it's possible to keep this merged in! I can create a new Pull also if its easier

**Comment by BlakeCampbells** [comment]
@OneMohrTime I went ahead and added you back in #1310. Thanks for letting me know!

**Comment by OneMohrTime** [comment]
@BlakeCampbells you rock!

**Comment by jakeherp** [comment]
Re-added in #1312 with new URL.

**Pull request merged**
