### PR TITLE
feat: add precommit hook to lint fix data.js

### PR DESCRIPTION
**Pull request by iamandrewluca**

### CODE REVIEW

**Comment by HugoDF** [comment]
@iamandrewluca could we also add this as a GitHub action check?

**Comment by iamandrewluca** [comment]
Do you mean to run Eslint fix when data validate action is run?

**Comment by HugoDF** [comment]
Yep either that or as a separate step/action.

I think a lot of people don't pull down the repo to add themselves, they probably use the GitHub UI.

Another thought is that we're running a pre-commit hook, we might also need to have some setup/install instructions.

**Comment by iamandrewluca** [comment]
Ok, I'll think about this, and modify the PR

**Comment by HugoDF** [comment]
@iamandrewluca I'm tempted to say, let's get the conflicts resolved, merge this and open another PR to run lint in a GitHub Action (shouldn't be terribly difficult)

**Comment by iamandrewluca** [comment]
No worries, I'll rebase. And finish the PR in the evening

**Comment by iamandrewluca** [comment]
I think I'll add exlint fix to run with the action that generates readme file

**Comment by iamandrewluca** [comment]
Done. @wesbos @HugoDF

**Comment by HugoDF** [comment]
@iamandrewluca merge merge merge 😄

**Pull request merged**
