### PR TITLE
Adding Colin Principe - hopefully this commit is correct

### PR DESCRIPTION
**Pull request by FatherOfCurses**

### CODE REVIEW

**Comment by FatherOfCurses** [comment]
@HugoDF I had tried to do this pull request before and the automatic checks were failing, so I decided to delete the pull request and create a new one.  Can you review this request please?  I can't figure out how to add you.

**Comment by yevhenorlov** [comment]
@FatherOfCurses your uses page doesn't specify anything about your setup or personal configs. The idea of awesome-uses is to share personal setup preferences, not just the stack people are working with.

**Comment by FatherOfCurses** [comment]
Thank you Yevhen, I understand now what the content needs to be.

I will update my uses page and send you a note when it's done for your
review.

**Comment by FatherOfCurses** [comment]
@yevhenorlov I've updated my uses after looking at a couple of the other pages in the collection, I think it's in line with what you described.  Please review when you have the chance.

**Pull request merged**
