### PR TITLE
Ensure "uses" URLs doesn't 4xx/5xx  or other error

### LINKED ISSUE #306: Add URL validation to make sure people are linking their /uses page
Taking a look at some of the open PRs, people have linked their website but not their `/uses` page. Maybe we could add some sort of eslint rule to make sure the URL is correct?

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #306 

The idea behind this is to ping every URL and make sure it sends back a 2xx response.

Some of the issues I've seen:
- dead domains
- dodgy certificates
- lots of redirects (301 & 302) -> we should manually check these to make sure they're not just doing a `/uses` to `/uses` redirect
- domains that time out
- 404s

### CODE REVIEW

**Comment by HugoDF** [comment]
Sample output

```
Ping to "https://sam-cross.github.io/uses" failed with status: 404
Ping to "https://hussain4real.github.io/Portfolio/uses" failed with status: 404
Ping to "https://jasoncoryalvernaz.com/uses" failed with status: 301
Ping to "https://renepot.com/uses" failed with error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: renepot.com. is not in the cert's altnames: DNS:renepot.net, DNS:www.renepot.net
Ping to "https://scotttolinski.com/uses" failed with status: 301
Ping to "https://calypsobronte.me/uses" failed with status: 301
Ping to "https://glennreyes.com/uses" failed with status: 301
Ping to "https://bradgarropy.com/uses" failed with status: 301
Ping to "https://www.euperia.com/uses" failed with status: 301
Ping to "https://aless.co/uses" failed with status: 301
Ping to "https://kentcdodds.com/uses" failed with status: 301
Ping to "https://www.davidosomething.com/uses/" failed with status: 302
Ping to "https://speek.design/uses" failed with status: 301
Ping to "https://laurosilva.com/uses" failed with status: 301
Ping to "https://vincentramdhanie.com/uses" failed with status: 301
Ping to "https://joshuabarker.com/uses" failed with status: 301
Ping to "https://jonsuh.com/uses" failed with status: 301
Ping to "https://www.silvandiepen.nl/uses/" failed with status: 301
Ping to "https://abdisalan.com/uses" failed with status: 301
Ping to "https://pavel.dev/uses" failed with error: Error: certificate has expired
Ping to "https://pouria.dev/uses" failed with status: 301
Ping to "https://byurhanbeyzat.com/uses" failed with status: 301
Ping to "https://gokul.site/uses" failed with status: 301
Ping to "https://steveheyes.co.uk/uses" failed with status: 301
Ping to "https://www.richardpalaciosg.dev/uses" failed with status: 404
Ping to "https://benleivian.com/uses" failed with status: 301
Ping to "https://jeremymouzin.com/uses" failed with status: 301
Ping to "https://sanketgandhi.com/uses" failed with status: 404
Ping to "https://www.arcath.net/uses" failed with status: 301
Ping to "https://timothymiller.dev/uses" failed with status: 301
Ping to "https://ssmusoke.com/uses" failed with status: 301
Ping to "https://steven.vanloef.com/uses" failed with status: 301
Ping to "https://martinchammah.dev/uses" failed with status: 404
Ping to "https://racik.info/uses" failed with status: 404
Ping to "https://danielvanc.com/uses" failed with status: 301
Ping to "https://rafaelquintanilha.com/about#uses" failed with status: 301
Ping to "https://chiamakaikeanyi.dev/uses" failed with status: 301
Ping to "https://kaleighscruggs.com/uses" failed with status: 301
Ping to "https://terrygodier.com/uses" failed with status: 301
Ping to "https://kilinkis.me/uses" failed with error: Error: self signed certificate
Ping to "https://johngarrett.dev/uses" failed with status: 301
Ping to "https://hakaselogs.me/2020-01-10/what-i-use" failed with status: 301
Ping to "https://jamesmills.co.uk/uses" failed with status: 301
Ping to "http://carlosjunod.me/uses/" failed with status: 302
Ping to "https://elliotbonneville.com/uses" failed with status: 301
Ping to "https://nickjanetakis.com/uses" failed with status: 301
Ping to "https://mynameisyuri.com/uses" failed with status: 404
Ping to "https://tomhazledine.com/uses" failed with status: 301
Ping to "https://khriztianmoreno.dev/uses" failed with status: 404
Ping to "https://aendrew.com/uses" failed with error: Error: self signed certificate
Ping to "https://dominicode.com/uses" failed with status: 301
Ping to "https://www.mihaiserban.dev/uses" failed with status: 301
Ping to "https://wesbos.com/uses" failed with status: 301
Ping to "https://tforster.com/uses" failed with error: Error: Request timed out
Ping to "https://deanacus.com/uses/" failed with error: Error: Request timed out
Ping to "https://carloscharris.com/uses" failed with error: Error: Request timed out
Action failed with 56 URL fetch failures, see logs
```

**Comment by HugoDF** [comment]
Another cool one where they're redirecting to the "2020" version of the uses post https://www.davidosomething.com/uses/

**Comment by HugoDF** [comment]
As per the issue I'm switching the detection code up to just check that something isn't dead 👍

**Comment by HugoDF** [comment]
Which means a lot fewer "failures"

```
Ping to "https://sam-cross.github.io/uses" failed with status: 404
Ping to "https://hussain4real.github.io/Portfolio/uses" failed with status: 404
Ping to "https://renepot.com/uses" failed with error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: renepot.com. is not in the cert's altnames: DNS:renepot.net, DNS:www.renepot.net
Ping to "https://pavel.dev/uses" failed with error: Error: certificate has expired
Ping to "https://sanketgandhi.com/uses" failed with status: 404
Ping to "https://www.richardpalaciosg.dev/uses" failed with status: 404
Ping to "https://martinchammah.dev/uses" failed with status: 404
Ping to "https://racik.info/uses" failed with status: 404
Ping to "https://kilinkis.me/uses" failed with error: Error: self signed certificate
Ping to "https://mynameisyuri.com/uses" failed with status: 404
Ping to "https://khriztianmoreno.dev/uses" failed with status: 404
Ping to "https://aendrew.com/uses" failed with error: Error: self signed certificate
Ping to "https://tforster.com/uses" failed with error: Error: Request timed out
Ping to "https://deanacus.com/uses/" failed with error: Error: Request timed out
Ping to "http://carlosjunod.me/uses/" failed with error: Error: Request timed out
Ping to "https://carloscharris.com/uses" failed with error: Error: Request timed out
Ping to "https://pawelgrzybek.com/uses/" failed with error: Error: Request timed out
Action failed with 17 URL fetch failures, see logs
```

**Comment by HugoDF** [comment]
There will likely need to be a process to notify users whose /uses pages have been suspended.

**Comment by wesbos** [comment]
Looks good to me @HugoDF - merge it!

**Pull request merged**
