### PR TITLE
fix(data): merge webdev tag (#637)

### PR DESCRIPTION
**Pull request by nico-bachner**

### CODE REVIEW

**Review by gatarelib — COMMENTED** [review]
You would agree with me this is really not worth a PR
You basically contracted the word "Developer"

**Comment by nico-bachner** [comment]
No, that's not all there was to it. I noticed about 5 variations of "Web [insert whatever here]" and merged them to an all-encompassing term "Web Dev".

I should have made this clear in the PR description. Sorry about that.

If you have a problem with the opinionated approach, that's fine by me, but please do review this again.

**Comment by gatarelib** [comment]
I can see you changed one from "Web Development Teacher" to "Web Developer Teacher " though

**Comment by nico-bachner** [comment]
Ah... 
Should I leave that one as it is, or merge it into Web Dev?

**Comment by BlakeCampbells** [comment]
I'm going to close this out for now. If we want to combine tags in the future feel free to reopen. 🙂

**Pull request closed without merging**
