### PR TITLE
Add Arisa Fukuzaki

### PR DESCRIPTION
**Pull request by schabibi1**

### CODE REVIEW

**Review by BlakeCampbells — CHANGES_REQUESTED** [review]
Please don't request changes to the readme.

**Review by schabibi1 — COMMENTED** [review]
Sorry about requesting changes to README. As I'm the PR author, I can't approve my own PR to apply your change request.

Could you help me to approve your changes? @BlakeCampbells

**Comment by BlakeCampbells** [comment]
@schabibi1 What might be easier is making a new PR then updating data.js to add yourself there. 

You should be able to make modifications to this branch without approval though. Approval is for merging this into the master branch.

**Comment by schabibi1** [comment]
Thanks, @BlakeCampbells , I'll create a new PR👍

**Comment by schabibi1** [comment]
@BlakeCampbells Created a new PR in #1268 

Could you take a look?

**Pull request closed without merging**
