### PR TITLE
Add @praveenpuglia

### PR DESCRIPTION
**Pull request by praveenpuglia**

### CODE REVIEW

**Comment by praveenpuglia** [comment]
@wesbos 
What should I do about this?
```
First-time contributors need a maintainer to approve running workflows. Learn more.
5 failing checks
```

I looked at the Netlify's logs but can't really find a mistake in the code I submitted.
```
1:01:44 AM: > 27 |   const twitter = `https://unavatar.now.sh/twitter/${person.twitter.replace('@', '')}`;
1:01:44 AM:      |                                                                     ^
1:01:44 AM:   28 |   const website = `https://unavatar.now.sh/${url.host}`;
1:01:44 AM:   29 |   const unavatar = person.twitter ? `${twitter}?fallback=${website}` : website;
1:01:44 AM:   30 |   const img = `https://images.weserv.nl/?url=${unavatar}&w=100&l=9&af&il&n=-1`;
1:01:44 AM: 
1:01:44 AM:   WebpackError: TypeError: Cannot read property 'replace' of null
```

**Comment by Nodirbek-Sharipov** [comment]
same here

**Comment by baadaa** [comment]
I saw the same error, and suggested a fix in my PR #1227 . I believe it resolves it when I tested locally and via Netlify. Hope the PR gets merged soon.

**Review by BlakeCampbells — APPROVED** [review]
I merged the latest fixes into your branch and it pass CI now. Sorry for the delay!

**Comment by praveenpuglia** [comment]
Thanks a ton!

**Pull request merged**
