### PR TITLE
Add Andri Soone

### PR DESCRIPTION
**Pull request by ndri**

### CODE REVIEW

**Review by BlakeCampbells — COMMENTED** [review]
Hey Andri, right now the build process requires the twitter attribute. This could be something we remove eventually, but that's why this is failing.

**Comment by ndri** [comment]
Thanks for letting me know! I won't make a twitter account for this, so I'll wait until Mastodon is supported.

**Comment by BlakeCampbells** [comment]
> Thanks for letting me know! I won't make a Twitter account for this, so I'll wait until Mastodon is supported.

Shoot, I didn't even see the `Mastodon,` so that might be what's throw the error. 

Sorry, I'm still getting used to this project.

**Comment by BlakeCampbells** [comment]
@ndri If we support Mastadon in the future I'll reopen this PR and get it merged in. 

Sorry about the Twitter requirement for now.

**Pull request closed without merging**
