### PR TITLE
Add Marty Romero @martyromero martyromero

### PR DESCRIPTION
**Pull request by martyromero**

### CODE REVIEW

**Review by HugoDF — CHANGES_REQUESTED** [review]
Could we do the same without deleting other people?

**Comment by martyromero** [comment]
Hi All, 

I am kind of new and not sure if I need to make any changes on this. Happy to.

**Comment by HugoDF** [comment]
> Hi All, 
> 
> I am kind of new and not sure if I need to make any changes on this. Happy to. 

Yeah, you haven't just added yourself, you also deleted 2 existing entries, if you put back the deleted entries I'm happy to merge this

**Comment by martyromero** [comment]
Have no idea how that happened. Added these back though. Thank you!

**Review by HugoDF — APPROVED** [review]

**Pull request merged**
