### PR TITLE
Add Scott Spence

### PR DESCRIPTION
**Pull request by spences10**

### CODE REVIEW

**Comment by wesbos** [comment]
Could you rebase? Or just close and make the PR again from the latest `website` branch

**Comment by spences10** [comment]
I'll rebase, I just did it in the web UI but no probs yeah!

Shoul dI check myself off the list too?

**Comment by wesbos** [comment]
sorry so many people PR-ing irght now it gets scrambled 

And yes :)

**Comment by spences10** [comment]
No worries, I'll wait for things to calm down and do it.

Thanks

**Pull request closed without merging**
