### PR TITLE
feat: add action to generate readme.md from data.js

### LINKED ISSUE #155: Programatically populate the readme.md
Once almost everyone is moved over, I'd like to make a github action that will generate the readme.md from the data.js file

Any references on how to do this are appreciated :)

### PR DESCRIPTION
**Pull request by iamandrewluca**
example https://github.com/iamandrewluca/awesome-uses/actions

`"type": "module"` was added in `package.json` so node could use esm imports

Closes #155

### CODE REVIEW

**Comment by wesbos** [comment]
Hey! Im using the esm package for this right now - take a look at the package.json - we are importing esm files. So this isn't needed

**Comment by wesbos** [comment]
oops I read this too quickly sorry will take a look soon

**Comment by wesbos** [comment]
Thanks -what is the process to hook it up to this repo?

**Comment by iamandrewluca** [comment]
I's already hooked, any commit in `website` branch that will modify `data.js` will trigger the action

**Comment by wesbos** [comment]
Oh dang! This is great! Thanks a ton for doing this!

**Comment by iamandrewluca** [comment]
@wesbos see also the PR with data validation :slightly_smiling_face:

**Pull request merged**
