### PR TITLE
Add Vikash Patel

### PR DESCRIPTION
**Pull request by vk4s**
Add Vikash Patel (@vk4s)'s uses page.

### CODE REVIEW

**Review by BlakeCampbells — CHANGES_REQUESTED** [review]
Hey @vk4s will you please update the country to the flag emoji?

Also let me know when your uses page is filled out and we'll get this merged in. 🙂

**Comment by vk4s** [comment]
Hi @BlakeCampbells, I have changed the country to an emoji.

**Review by BlakeCampbells — CHANGES_REQUESTED** [review]
Will you update your uses page to include some of your set-up? @vk4s

**Comment by vk4s** [comment]
> Will you update your uses page to include some of your set-up? @vk4s

Yes @BlakeCampbells, the page is not complete yet, I'm working on it. I'll request review after finishing the page 😀

**Review by BlakeCampbells — APPROVED** [review]
Perfect thanks!

**Pull request merged**
