### PR TITLE
feat: add Pull Request template

### LINKED ISSUE #413: Create Pull Request template to explain users what is a `/uses` page
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

### PR DESCRIPTION
**Pull request by sam-cross**
Adding a PR template, re https://github.com/wesbos/awesome-uses/issues/413.

Marked as draft for now in case anything else needs adding to it. **Here's an example:**

----
# awesome-uses

Please read the requirements corresponding to your pull request before you submit.

## data.js Requirements

* Ensure you are linking to a /uses page
* Ensure your data is formatted in the same way as other entries
* Ensure this PR has a title in the following format
    * ✅ Add Your Name
    * ✅ Add @twitterusername
    * ❌ Add myself
    * ❌ Adding myself!
    * ❌ Add Your Name @twitter @github

## Fix Requirements

* Ensure the code submitted is formatted similarly to existing code
* Ensure variable, method, function, and component names are clear and concise

## Final Requirements

* You've read and understood the above

## Finally...

**Add your name to verify:** Sam Cross

Closes #413

### CODE REVIEW

**Comment by iamandrewluca** [comment]
Can you please move the template in `.github/pull_request_template.md` ?

And also would be great to have a explanation what is a `/uses` page, what should include, because some people are just adding pages without any uses, just some ads and promoted content.

**Comment by sam-cross** [comment]
@iamandrewluca I'm adding a little more before this is closed

**Comment by iamandrewluca** [comment]
Oh.. )) merged already :)

**Comment by sam-cross** [comment]
Don't worry, I'll make another PR with additions. I've added some info about what should be included.

**Pull request merged**
