### PR TITLE
Adding @yabozdar@fosstodon.org

### PR DESCRIPTION
**Pull request by yabozdar**
I would like to be part of uses.tech network. My uses page is already available on the website as given in the data.

### CODE REVIEW

**Comment by yabozdar** [comment]
I would appreciate if my changes are accepted. Thanks.

**Comment by yabozdar** [comment]
I made the data changes that led the previous commit fail to merge.

**Comment by yabozdar** [comment]
@wesbos I am not sure why ping to my uses page is failing. It could be if you are using a private DNS to block new domains. My domain is new.

**Comment by wesbos** [comment]
not sure why it was 403ing, but it looks good

**Comment by yabozdar** [comment]
Thanks.

**Pull request merged**
