### PR TITLE
Upgrade to styled-components v5 beta

### PR DESCRIPTION
**Pull request by mxstbr**
Just as a test for us :angel: No need to merge this if you'd rather stay on a stable version.

### CODE REVIEW

**Comment by wesbos** [comment]
Is the API the same? Any breaking changes?

**Comment by mxstbr** [comment]
Should not have any! See https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987 

Apparently that didn't work, although the error seems unrelated? 🤔

**Comment by wesbos** [comment]
yeah sorry some goofball broke the build with a missing comma :) lets try it

**Comment by mxstbr** [comment]
Awesome, thank you @wesbos! 🙌

**Pull request merged**
