### PR TITLE
feat: comment on PR with validation outcome

### LINKED ISSUE #478: Feature: comment on PR with validation output
It seems possible to leave a comment on PRs when validation fails.

See  https://github.com/unsplash/comment-on-pr, code is obviously Ruby but equivalent functionality in JS should do the trick.

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #478 

Todo:
- [x] validate commenting works on failure
- [x] validate commenting works on success
~~- [ ] (maybe) try to take a screenshot~~ won't do, would need to take a screenshot of the site, upload it somewhere and leave a comment referencing it using markdown syntax.

### CODE REVIEW

**Comment by HugoDF** [comment]
test: ![]( data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFgAAABYCAIAAAD+96djAAAKpUlEQVR4nOyca0wj1fvH6XUbamG7dXe5lV1o1+DSWmkMFBNAixgxisILMIi+wERJhKg1IRolQSPhhYmXSMRg0BhESQDRGAUhMUSJsbQpULFNgRYo91pKKwWpvf2Tnf6b+bWdM2emM+wvv/Tz6nT69DnP+c4zM2fOPFM2g8FIS5GWxrzdAfy3kBIiQkqICCkhIqSEiJASIkJKiAgpISKwz7OzK1euFBYWSqXS/Px8kUiUmZkpEAiYTCaDwQiFQse3cLlcW1tbVqvVZrPt7u6GQqFzCo5BM0wms7S09KOPPtre3g7jEQqF0B9dLtcXX3zx8MMPc7lcuuOkUQgej/fSSy9tbGzgjh+Xw8PDt99+WygU0hct9ULw+fxnn312bGzM7XYnLwGaf/75Z2ZmpqOjQyQSUR42xUJUVVWtrq5SO/54Dg4Onn76aeTkQhWUCZGTk/P111/HHOS08uuvv95zzz1UxU+NEJWVlU6nM3TunJ2dNTU1UTKEZIUQCoXvvPPOycnJuSVCDH6/f3BwsKCg4HYKIZFItra2bpcEaLxeb3l5+e0Rgs/n63Q6JEWRKUC0Hf0Y34A0iG/jGmxuborF4vMWQiAQzM7Okh4nTQY2m430MUJGCKVSaTKZzj39oTg4OHjyySfPQwipVOr1emm6TKLdJuwCxiAYDFZVVdEuxOjoKB0SUItOp2OxWDQK8cYbbwBywWQy6fX6g4MDusfpcrkWFhYMBkMgEMCyGR4evnDhAi1CtLa2AoLb3t5ms9mI5b333tvT07Ozs0Pt+D0ezyeffPLAAw9EO/rxxx8B9n19fdQLIRaLwTdR/f39MT+5cOFCd3e33++nRIWBgYGLFy/GdPH8888DfhIMBtVqNbwWUE+6xsbG6uvrAQZPPfXU6Oho/HaZTPbee+9VV1ejN7pcLrvd7rjF2dlZMBhMT08XiUSXL1/Oy8vLyspCR2U2m1955ZWZmZl451Kp1GKxJFxkCYfDaWlpKysrcrk8EAjgDhBKiJqamp9++glsIxaLd3Z2sL5tampSKBRms3ltbW1lZeXw8BDgKiMjQyqVSiSSoqIip9P56aefAkZydHSUmZkJ8NbW1jYwMAAOPg1yhWpqagqct4FAgEAGUgruXb/FYoHxg794m5eX9+CDD6alpSF+ow102+fz4UtODz6fDxBYOBy+6667HnnkEVw/+EK8/PLLXC4XvSX+aEIuVMRHQQE8Hg/XprOzE98ROGEKCgq8Xi849xCkUilFyU4ANpt9fHyMG1soFKqtrQW7wskIjUbD5/PjtyPphybmunA+KJXKO+64A70FHVi0zWAw3nzzTbArkBAsFquxsTHhV/EHgkqlwgubesrKymK2oANDt1Uq1ZUrV0C+ANlSXl4Oc1CEw2Gj0UjrWjsWHA4H94oWpbm5GeAKlBGVlZWQe+a1115zu92QxhQSCAQ0Gg3k0zDwcEBCFBcXw3RgsVimp6dhLOnAbDaPj4/DWOIMB5AtWq0WY/X4P3juuedoyHoCKJXKYDCIDgm9nBXF4XAAnGAKwWKxPB4P7oG3sbHB4/HoGSABwLehUQoLC7E8YB4aEokkIyMDN99GR0dv47QyyvDwMIxZaWkp1leYZQGFhYUxl2KkHW0g7fn5eeJhU49Wq00YbUzkBQUFWB4wM0IsFkfbMbMG9Me1tbXkhkANdrvd7/fjmuXn52N9hSlEbm5u9FSKbEnY3t3dJRU5xfj9/uPj4+gBj74IoKNFBpUQTCEuX74M6DiaeDBrHudDMBjEmmJHAQwKUwgmEzTFiKYGh8MhEi2NsNlswBQbATCoZIvJrl69mqQHSmCz2TF3X0TBFAIy569du5ZM91SRlZUFk5uAEyqmEC6XCyYCiUQCY0Y3UqkUxuzo6AjrK8x5hNPpjD/ZxKNQKGAioBuFQgETrdPpxPoKUwir1Qq5wM3hcGCu4bTy6KOPwkQLmPVgHhrLy8swEeTk5NTU1MBY0kdubq5arYax/PPPP7G+whRie3sbXRAEWMVuaWkhOwRqQCrssFax0ZEDhADdhi8vLycszIgp0jg7O7vzzjuTu3skD5vNXl9fhymp8Xq9gEfkoHnE4uIiYoSWLKaNPONsb2+neC9D09LScv36daxpNbq9tLQEWssCiN3R0YF1Yx9THOD1epOvayMBn8+32+1YgcUE+f777wNcgTJiYWEBIB/6I5/P/+abbwQCAcndSgomk/nZZ5+h75LBU2zAcNLAGcHj8fb29mBWfhBMJtNDDz1Ew45PgFwu//nnn+Fj8/v9eXl5AIc4T7reeust+M4QOjs7qR51LM3Nzf/++y+hqL7//nuwTxwhrl+/nrDSA6nZSthlKBSamJigsEoazbVr1/r7+0kUnzzxxBNgz/hlARMTEzHLwbOzs9nZ2RwOp6ysbGxsLBAIxC8ZBwKB6elpCo+U+++/H1kfhVlYj8Fms0WrjUCAz0lFRUUGgwH90Pmvv/568cUXx8fHBQJBbW2tyWT6/PPPlUplwp87HI7l5WWj0WixWPb29vR6PcyillAorKyszM7OvnHjhkwmKy4uzsnJwf1VQsLhcENDw3fffYdjB7M3RkZG4pNtbm4OmUdpNJr6+nqYtX+9Xp+eng7TI5PJ/Oqrr4jmf0K0Wi1Mj1BCPPbYYwlLgUdGRhgMxqVLl65evdra2gqY1SFVNSUlJTDdIYhEIuQOGOAWpli7o6ODMiE4HI7ZbI72ge6moaGBwWBUVFQ888wz09PTgELpH374AV4FhN7e3iSF+PvvvyHfe4ItL5TJZA6HIz7x3G63QqEQCoVqtTozM3NoaAirIpVEibREIkmm1tnn8+FeLAgLwWAw1Gp1tNIVHd9vv/2GGPT09HzwwQcajSb+Im+1WjMyMogKwWAw9vf30X4IFWtrNBpincGfgXt6el5//fX47Tdu3LBarVlZWRUVFRMTEyqVSi6Xy2Sy9PT09fV1vV7/yy+/eL1ewmf8WzfOd999N4kfTk5OPv744wTenyUkGYvF+vbbb+P3w8cffxy1EYvFX375ZW5uLpfLHR4e5nK5VVVV3d3dxHbO/2MwGEgcFDqdjmgCEq7OF4lEMTd8SEK2tbURdQXDwsICURVOT0+LioqIdkTmxZWbN2/GnziDweCHH34oEAhIOARANCN8Pl9dXR2Jjki+ylRSUuJwOOIns7u7uy+88EK8HJcuXSLXkcFgwJg3J8Dn8zU2NpLriPzLbfn5+b///nvC3eL3+7e2toxG4/z8vMlk2t/fPzw8JNcLfEasrq7ed999pIeT1OuOFy9enJubg4nS7XaT62JxcRHG//r6OrJgR5qknn16PJ7q6uq+vj50TAlXkJMpUAa4RdpTU1OlpaWbm5vJjIWaV6K7urqiE1skvpiprsfjIed5cXERPMUeHBwk+vpWQih7Sb68vHxoaOj09DRh6qKrOAixtLSU0GEgEJicnKyrq6PqPwMo/tuE7OzshAVuJycn5CL+448/0H6QdNDpdHK5nNrIqf8jDRaL1dzcHDMRoioj7Hb7q6++SkdBI41/rXLz5s2uri6tVmuz2Xp7e8k5aW9vX1tbMxqN7777rkqlglpxI01SJ9v/FVL/QxUhJUSElBARUkJESAkRISVEhJQQEVJCRPi/AAAA//8oLyMhC6vhyAAAAABJRU5ErkJggg==)

**Comment by iamandrewluca** [comment]
@HugoDF interesting feature 😄

**Comment by sam-cross** [comment]
Messages should be clearer and nicer to read, but that's not crucial at the moment. Nice work, this is great!

**Comment by HugoDF** [comment]
@sam-cross yeah I thought so too, but couldn't come up with anything better. Feel free to tinker with the comments strings 😊

**Pull request merged**
