### PR TITLE
Pawel Grzybek — add my /uses website to the list

### PR DESCRIPTION
**Pull request by pawelgrzybek**
[https://pawelgrzybek.com/uses/](https://pawelgrzybek.com/uses/)

### CODE REVIEW

**Comment by igauravsehrawat** [comment]
@pawelgrzybek  Looks good but I think little description about softwares https://pawelgrzybek.com/uses/#software should be given, like [wesbos](https://wesbos.com/uses/) has done.

**Comment by pawelgrzybek** [comment]
I will add some more details about every piece of sw & hw on this list. On my list to do :)

**Comment by igauravsehrawat** [comment]
@pawelgrzybek Hey, I can you reopen the PR? since you have added description.
I forgot to check it. My bad.

Also there are two lines in your PR, it would be nice if you fix it too.

Thanks.

**Comment by pawelgrzybek** [comment]
Hi.

I submitted a new PR for clarity reasons. This one is nor relevant anymore, look at the new one #60

**Pull request closed without merging**
