### PR TITLE
Re-add @narze

### PR DESCRIPTION
**Pull request by narze**
My entry was deleted by #1519, I'm re-adding it since I just changed my domain name

### CODE REVIEW

**Comment by narze** [comment]
I'm not sure why the build is failing, can you retry the build?

**Review by BlakeCampbells — CHANGES_REQUESTED** [review]
It looks like the `uses` page is redirecting. Will you take a look?

**Comment by narze** [comment]
> It looks like the `uses` page is redirecting. Will you take a look?

I've fixed it (case-sensitivity issue) now the URL https://garden.narze.live/uses is working

**Review by BlakeCampbells — APPROVED** [review]

**Comment by BlakeCampbells** [comment]
Sorry, for the long wait to get this in. I must have missed the newest commit.

**Pull request merged**
