### PR TITLE
Add @rasliche's /uses page

### PR DESCRIPTION
**Pull request by rasliche**

### CODE REVIEW

**Comment by iamandrewluca** [comment]
Please why is the need to add yourself to this list for the sake of being in it, and also not having any `/uses` page related to tech.

*readme.md*
> A list of /uses pages detailing developer setups, gear, software and configs.

http://uses.tech/

**Comment by rasliche** [comment]
Fixed the page. Forgot just how little I had published from drafts... Sorry for wasting your time earlier. Hope this new version is acceptable. It'll keep getting better and better as I work on it but the bones are there now.

**Comment by iamandrewluca** [comment]
Better now. No worries :slightly_smiling_face: please resolve conflict and we are good to go.

**Comment by iamandrewluca** [comment]
Please take a look at resolved conflicts, it alters another user data

**Comment by rasliche** [comment]
Yeah sorry, I'm working on it. Trying to figure out github. It was fine when I originally submitted it but when I opened it up again the other person's data was right in the middle of mine...

**Comment by iamandrewluca** [comment]
Yes, not is a bit complicated. We will find in future a solution to make adding other persons without modyfing data.js file.

**Comment by rasliche** [comment]
It looks like it's failing because someone else's link is timing out? Is that right or is there still something I need to fix for my data section?

**Comment by iamandrewluca** [comment]
If is failling because of another user, we will still merge the PR.

**Comment by rasliche** [comment]
Great. Thank you. This has been... an experience. Thank you for your patience as I figured it out.

**Comment by rasliche** [comment]
Yeah why does that keep happening? I don't want to seem like I have an attitude, I just don't understand. _I_ didn't delete anyone... my fork was fine until @iamandrewluca (fairly) didn't merge it. When I went back, James' data was conflicting _with mine_.

And my data was fine yesterday, but now someone else's is conflicting with it again? What am I missing?

**Comment by HugoDF** [comment]
@rasliche the reason there was a conflict is because both you and others are updating the same file/in the same spot in the file.

When you solved the conflict instead of keeping both the current changes and your data, you removed existing data and replaced it with your. 

I wouldn't bother with this PR, the conflicts are only going to get worse, I would suggest you start from the top (delete your fork, fork again and make your changes).

**Comment by HugoDF** [comment]
Merged your other PR, welcome to git collaboration

**Comment by rasliche** [comment]
Yeah, geez, thanks. What a wild ride.

**Pull request closed without merging**
